In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys
sys.path.append('..')

from wildlife_datasets import datasets, loader, analysis, evaluation, splits
import numpy as np
import sklearn.metrics as skm

In [32]:
def compute_metrics(y_true, y_pred):
    score1 = skm.accuracy_score(y_true, y_pred)
    score2 = skm.balanced_accuracy_score(y_true, y_pred)
    score3 = skm.precision_score(y_true, y_pred, average='macro')
    score4 = skm.recall_score(y_true, y_pred, average='macro')
    score5 = skm.f1_score(y_true, y_pred, average='macro')
    return score1, score2, score3, score4, score5
    
def macro_f1(ps, rs):
    return np.mean([0 if (p,r)==(0,0) else 2*p*r/(p+r) for (p, r) in zip(ps, rs)])

In [33]:
y_true = [1,1,2,3,3]
y_pred = [1,1,2,3,1]

In [34]:
print(skm.confusion_matrix(y_true, y_pred))
print(compute_metrics(y_true, y_pred))
print((4/5, (2/2+1/1+1/2)/3, (2/3+1/1+1/1)/3, (2/2+1/1+1/2)/3), macro_f1([2/3,1/1,1/1], [2/2,1/1,1/2]))

[[2 0 0]
 [0 1 0]
 [1 0 1]]
(0.8, 0.8333333333333334, 0.8888888888888888, 0.8333333333333334, 0.8222222222222223)
(0.8, 0.8333333333333334, 0.8888888888888888, 0.8333333333333334) 0.8222222222222223


In [35]:
y_true = [1,1,2,3,3]
y_pred = [1,1,2,3,0]

In [36]:
print(skm.confusion_matrix(y_true, y_pred))
print(compute_metrics(y_true, y_pred))
print((4/5, (2/2+1/1+1/2)/3, (0/1+2/2+1/1+1/1)/4, (0+2/2+1/1+1/2)/4, macro_f1([0/1,2/2,1/1,1/1], [0,2/2,1/1,1/2])))

[[0 0 0 0]
 [0 2 0 0]
 [0 0 1 0]
 [1 0 0 1]]
(0.8, 0.8333333333333334, 0.75, 0.625, 0.6666666666666666)
(0.8, 0.8333333333333334, 0.75, 0.625, 0.6666666666666666)


/mnt/appl/software/scikit-learn/1.0.1-foss-2021b/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1953: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/mnt/appl/software/scikit-learn/1.0.1-foss-2021b/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [50]:
y_true = [1,1,2,3,3]
y_pred = [1,1,2,3,0]
e = evaluation.ClosedSet()
y_true, y_pred = e.modify_classes(y_true, y_pred)
print(skm.confusion_matrix(y_true, y_pred))
print(compute_metrics(y_true, y_pred))

[[2 0 0]
 [0 1 0]
 [0 1 1]]
(0.8, 0.8333333333333334, 0.8333333333333334, 0.8333333333333334, 0.7777777777777777)


In [41]:
y_true, y_pred

([1, 1, 2, 3, 3], [1, 1, 2, 3, 0])

In [ ]:
known_classes = [1,2,3]
y_true = [1,2,3,4,5]
y_pred = [1,2,3,'new','new']

In [ ]:
y_true = [y if y in known_classes else 'new' for y in y_true]

In [54]:
[i for i in [1, None, 2]]

[1, None, 2]

In [59]:
np.sort(['a', 'qwe', 'qwe_new'])

array(['a', 'qwe', 'qwe_new'], dtype='<U7')

In [63]:
np.hstack((np.array(['a', 'qwe', 'qwe_new']), ['a', 'qwe', 'qwe_new']))

array(['a', 'qwe', 'qwe_new', 'a', 'qwe', 'qwe_new'], dtype='<U7')

In [70]:
dir(evaluation)

['ClosedSet',
 'DisjointSet',
 'OpenSet',
 '__builtins__',
 '__cached__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 'accuracy',
 'modify_y',
 'np',
 'recognize_id_split',
 'splits']

In [44]:
evaluation.unify_types([1,'123',1], [1,20,'123'], '123')

([1, 0, 1], [1, 20, 0], 0)

In [38]:
str in [type(y) for y in [1,'a']]

True

In [17]:
np.array([1,2,3]) == 'a'

/tmp/ipykernel_3143/1558224492.py:1: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  np.array([1,2,3]) == 'a'


False

In [6]:
np.sort(list({1,2,3}))

array([1, 2, 3])

In [26]:
y_true=9*[1,2]
y_true.append(1)
y_true.append(2)
y_pred=9*[1,2]
y_pred.append(3)
y_pred.append(4)

print(compute_metrics(y_true, y_pred))

(0.9, 0.9, 0.5, 0.45, 0.4736842105263158)


/mnt/appl/software/scikit-learn/1.0.1-foss-2021b/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1953: UserWarning: y_pred contains classes not in y_true
  warnings.warn("y_pred contains classes not in y_true")
/mnt/appl/software/scikit-learn/1.0.1-foss-2021b/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [22]:
y_true

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, [1, 2]]

In [8]:
y_true = [1,1,2,3,3]
y_pred = [1,1,2,3,1]

In [9]:
evaluation.accuracy(y_true, y_pred)

0.8